export const SET_ASIDE = 'SET_ASIDE';
export const SET_MODAL_REJECT_ORDER = 'SET_MODAL_REJECT_ORDER'
export const SET_MODAL_PAYMENT_RECEIPT = 'SET_MODAL_PAYMENT_RECEIPT'
export const SET_MODAL_DELETE_ORDER = 'SET_MODAL_DELETE_ORDER'